CREATE TABLE REG_ADDRESS (
  ID INT NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  SETTLE_DATE CHAR(8) NOT NULL,
  PASSPORT_FK INT NOT NULL,

  PRIMARY KEY (ID)
);

ALTER TABLE REG_ADDRESS
    ADD CONSTRAINT FK_ADDRESSES_PASSPORTS
    FOREIGN KEY (PASSPORT_FK) REFERENCES PASSPORT(SERIES, NUMBER);

CREATE TABLE DEPARTMENT (
  ID INT NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  CITY VARCHAR(100) NOT NULL,

  PRIMARY KEY (ID)
);

CREATE TABLE PERSON (
  ID INT NOT NULL,
  FULL_NAME VARCHAR(255) NOT NULL,
  DOB CHAR(8) NOT NULL,

  PRIMARY KEY (ID)
);

CREATE TABLE PASSPORT (
  SERIES CHAR(4) NOT NULL,
  NUMBER CHAR(6) NOT NULL,
  CHILDREN VARCHAR(255) NULL,
  RELATIONSHIP BOOLEAN NOT NULL,
  PHOTO BLOB NOT NULL,

  IS_TEMP BOOLEAN NULL,
  END_DATE BOOLEAN NULL,

  ADDR_FK INT REFERENCES REG_ADDRESS(ID)
ON UPDATE CASCADE ON DELETE RESTRICT,

  DEPARTMENT_FK INT REFERENCES DEPARTMENT(ID)
ON UPDATE CASCADE ON DELETE RESTRICT,

  PERSON_FK  INT REFERENCES PERSON(ID)
ON UPDATE CASCADE ON DELETE RESTRICT,

PRIMARY KEY (SERIES, NUMBER)
);
ALTER TABLE PASSPORT
  ADD CONSTRAINT FK_PASSPORTS_ADDRESSES
FOREIGN KEY(ADDR_FK) REFERENCES REG_ADDRESS(ID)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PASSPORT
  ADD CONSTRAINT FK_PASSPORTS_DEPS
FOREIGN KEY(DEPARTMENT_FK) REFERENCES DEPARTMENT(ID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE PASSPORT
  ADD CONSTRAINT FK_PASSPORTS_PERSONS
FOREIGN KEY(PERSON_FK) REFERENCES PERSON(ID)
ON UPDATE CASCADE ON DELETE CASCADE;
